---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: home-service
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          fsGroupChangePolicy: "OnRootMismatch"
        volumeMounts:
          - name: timezone
            mountPath: /etc/localtime
          - name: config
            mountPath: /etc/nginx/conf.d
          - name: ssl
            mountPath: /etc/nginx/ssl
      nodeName: k3s-node-001
      volumes:
        - name: timezone
          hostPath:
              path: /etc/localtime
        - name: config
          hostPath:
              path: /app/nginx/config
              type: DirectoryOrCreate
        - name: ssl
          hostPath:
              path: /app/nginx/ssl
              type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: home-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000