---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-index-data
            mountPath: /usr/share/nginx/html
          - name: timezone
            mountPath: /etc/localtime
      volumes:
        - name: timezone
          hostPath:
              path: /etc/localtime
        - name: nginx-index-data
          persistentVolumeClaim:
            claimName: nginx-index
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-index
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000