apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
spec:
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: linuxserver/qbittorrent:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        - name: TZ
          value: "Asia/Shanghai"
        - name: UMASK_SET
          value: "022"
        - name: WEBUI_PORT
          value: "8080"
        resources:
          limits:
            memory: "1024Mi"
            cpu: "1000m"
        livenessProbe: 
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 10
        readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 10
        ports:
        - containerPort: 8080
          name: qbittorrent-wbe
          protocol: TCP
        - containerPort: 6188
          name: qbit-sync-udp
          protocol: UDP
        - containerPort: 6188
          name: qbit-sync-tcp
          protocol: TCP
        volumeMounts:
          - name: qbittorrent-config
            mountPath:  /config
          - name: qbittorrent-downloads
            mountPath: /downloads
        securityContext:
          privileged: true
      volumes:
        - name: qbittorrent-config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: qbittorrent-downloads
          persistentVolumeClaim:
            claimName: qbittorrent-downloads
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qbittorrent-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qbittorrent-downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: qbit-svc
  labels:
    app: qbittorrent
spec:
  ports:
  - name:  qbit-web-ui
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name:  qbit-sync-udp
    port: 6881
    protocol: UDP
    targetPort: 6881
  - name: qbit-sync-tcp
    port: 6881
    protocol: TCP
    targetPort: 6881
  selector:
    app: qbittorrent
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:  qbit-web-ui
  labels:
    app: qbittorrent
spec:
  rules:
  - host: qbit.iosa.vip
    http:
      paths:
      - backend:
          serviceName: qbit-svc
          servicePort: 8080
        path: /
status:
  loadBalancer:
    ingress:
    - ip: 10.168.10.101